{
 "title": "idmsvc-backend",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Host enrollments per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(idmsvc_http_request_duration_seconds_count{path=\"/api/idmsvc/v1/host-conf/:inventory_id/:fqdn\"}[1d])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Top 10 requests in 24 hours",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, sum by(method, path, status) (rate(idmsvc_http_request_duration_seconds_count[24h]))) * 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests count per 1hr",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(path, method) (rate(idmsvc_http_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  },
  {
   "title": "95th percentily request latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method, path) (rate(idmsvc_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{path}} - {{method}}"
    }
   ]
  }
 ]
}