// Code generated by mockery v2.53.3. DO NOT EDIT.

package middleware

import (
	identity "github.com/redhatinsights/platform-go-middlewares/v2/identity"

	mock "github.com/stretchr/testify/mock"
)

// IdentityPredicate is an autogenerated mock type for the IdentityPredicate type
type IdentityPredicate struct {
	mock.Mock
}

// Execute provides a mock function with given fields: data
func (_m *IdentityPredicate) Execute(data *identity.XRHID) error {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*identity.XRHID) error); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIdentityPredicate creates a new instance of IdentityPredicate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIdentityPredicate(t interface {
	mock.TestingT
	Cleanup(func())
}) *IdentityPredicate {
	mock := &IdentityPredicate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
