// Code generated by mockery v2.53.3. DO NOT EDIT.

package middleware

import (
	rbac_data "github.com/podengo-project/idmsvc-backend/internal/infrastructure/middleware/rbac-data"
	mock "github.com/stretchr/testify/mock"
)

// RBACPermissionValidator is an autogenerated mock type for the RBACPermissionValidator type
type RBACPermissionValidator struct {
	mock.Mock
}

// Execute provides a mock function with given fields: p
func (_m *RBACPermissionValidator) Execute(p rbac_data.RBACPermission) rbac_data.RBACPermission {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 rbac_data.RBACPermission
	if rf, ok := ret.Get(0).(func(rbac_data.RBACPermission) rbac_data.RBACPermission); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(rbac_data.RBACPermission)
	}

	return r0
}

// NewRBACPermissionValidator creates a new instance of RBACPermissionValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRBACPermissionValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *RBACPermissionValidator {
	mock := &RBACPermissionValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
