// Code generated by mockery v2.53.3. DO NOT EDIT.

package middleware

import (
	identity "github.com/redhatinsights/platform-go-middlewares/v2/identity"

	mock "github.com/stretchr/testify/mock"
)

// XRhIValidator is an autogenerated mock type for the XRhIValidator type
type XRhIValidator struct {
	mock.Mock
}

// ValidateXRhIdentity provides a mock function with given fields: xrhi
func (_m *XRhIValidator) ValidateXRhIdentity(xrhi *identity.XRHID) error {
	ret := _m.Called(xrhi)

	if len(ret) == 0 {
		panic("no return value specified for ValidateXRhIdentity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*identity.XRHID) error); ok {
		r0 = rf(xrhi)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewXRhIValidator creates a new instance of XRhIValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewXRhIValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *XRhIValidator {
	mock := &XRhIValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
