// Code generated by mockery v2.16.0. DO NOT EDIT.

package middleware

import (
	identity "github.com/redhatinsights/platform-go-middlewares/identity"

	mock "github.com/stretchr/testify/mock"
)

// XRhIValidator is an autogenerated mock type for the XRhIValidator type
type XRhIValidator struct {
	mock.Mock
}

// ValidateXRhIdentity provides a mock function with given fields: xrhi
func (_m *XRhIValidator) ValidateXRhIdentity(xrhi *identity.Identity) error {
	ret := _m.Called(xrhi)

	var r0 error
	if rf, ok := ret.Get(0).(func(*identity.Identity) error); ok {
		r0 = rf(xrhi)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewXRhIValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewXRhIValidator creates a new instance of XRhIValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewXRhIValidator(t mockConstructorTestingTNewXRhIValidator) *XRhIValidator {
	mock := &XRhIValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
