### This file is used by ipa-hcc CI jobs
---
version: "3.0"
services:
  database:
    image: quay.io/cloudservices/postgresql-rds:15
    environment:
      - POSTGRESQL_DATABASE=${DATABASE_NAME:-idmsvc-db}
      - POSTGRESQL_USER=${DATABASE_USER:-idmsvc-user}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD:-idmsvc-secret}
    ports:
      - ${DATABASE_EXTERNAL_PORT:-5432}:5432/tcp
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready"
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  backend-service:
    image: ${CONTAINER_IMAGE_BASE:-idmsvc-backend}:${CONTAINER_IMAGE_TAG:-latest}
    build:
      dockerfile: build/package/Dockerfile
      context: ..
      tags:
        - ${CONTAINER_IMAGE_BASE:-idmsvc-backend}:${CONTAINER_IMAGE_TAG:-latest}
    environment:
      - WEB_PORT=8000
      - DATABASE_HOST=database
      - DATABASE_NAME=${DATABASE_NAME:-idmsvc-db}
      - DATABASE_USER=${DATABASE_USER:-idmsvc-user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-idmsvc-secret}
      - APP_SECRET=${APP_SECRET:-YTEzY2YxNjAtNTU5MzExZWY5NzcxZmExNjNlNzMwZmM1}
      - APP_VALIDATE_API=${APP_VALIDATE_API:-false}
      - APP_TOKEN_EXPIRATION_SECONDS=${APP_TOKEN_EXPIRATION_SECONDS:-3600}
      - CLIENTS_RBAC_BASE_URL=http://mock-rbac:8020/api/rbac/v1
      - LOGGING_LEVEL=${LOGGING_LEVEL:-debug}
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    ports:
      - 8000:8000/tcp
    restart: "on-failure:5"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/private/readyz"]
      interval: 5s
      retries: 10
      timeout: 3s
      start_period: 5s

  mock-rbac:
    image: "${MOCK_RBAC_CONTAINER}"
    build:
      dockerfile: build/mock-rbac/Dockerfile
      context: ../
    environment:
      CLIENTS_RBAC_BASE_URL: http://0.0.0.0:8020/api/rbac/v1
      APP_CLIENTS_RBAC_PROFILE: ${APP_CLIENTS_RBAC_PROFILE:-domain-admin}
      CONFIG_PATH: /opt/etc
      # APP_CLIENTS_RBAC_PROFILE: super-admin
      # APP_CLIENTS_RBAC_PROFILE: domain-read-only
      # APP_CLIENTS_RBAC_PROFILE: domain-no-perms
      # APP_CLIENTS_RBAC_PROFILE: custom
    ports:
      - 8020:8020
    volumes:
      - ../configs/config.yaml:/opt/etc/config.yaml:z

volumes:
  database:
