# https://consoledot.pages.redhat.com/clowder/dev/api_reference.html
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: idmsvc

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: ${APP_NAME}-backend
    spec:
      envName: ${ENV_NAME}
      testing:
        iqePlugin: idm
      # FIXME Update dependencies when integration with rbac is made
      # dependencies: ["rbac"]
      # https://consoledot.pages.redhat.com/clowder/dev/providers/dependencies.html
      dependencies: ["rbac"]

      # https://consoledot.pages.redhat.com/clowder/dev/providers/deployment.html
      deployments:
        # TODO Rename to your service-name deployment name
        - name: service
          # NOTE minReplicas is deprecated, but not sure if this change exist further
          # than the ephemeral environment. When both values exist, replicas has
          # priority over minReplicas
          # https://github.com/RedHatInsights/clowder/commit/aaf5643a7b1e769b53768e7c1a446d348d0a71f4
          minReplicas: ${{SERVICE_REPLICAS}}  # DEPRECATED
          replicas: ${{SERVICE_REPLICAS}}

          # https://consoledot.pages.redhat.com/clowder/dev/providers/web.html
          webServices:
            public:
              enabled: true
              # See: https://github.com/RedHatInsights/clowder/blob/e1af1adc4dcbc5d0a8b28b37c6e367fff843acda/apis/cloud.redhat.com/v1alpha1/clowdapp_types.go#L152
              apiPath: idmsvc
          podSpec:
            initContainers:
              - name: db-migrate-up
                inheritEnv: true
                args:
                  - /opt/bin/db-tool
                  - migrate
                  - up
                  - "0"
              - name: db-jwk-refresh
                inheritEnv: true
                args:
                  - /opt/bin/db-tool
                  - jwk
                  - refresh
            image: ${IMAGE}:${IMAGE_TAG}
            command:
              - /opt/bin/service
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /private/livez
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /private/readyz
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            env:
              - name: APP_NAME
                value: ${{APP_NAME}}
              - name: CLOWDER_ENABLED
                value: "true"
              - name: LOGGING_LEVEL
                value: ${{LOGGING_LEVEL}}
              - name: LOGGING_LOCATION
                value: ${LOGGING_LOCATION}
              - name: APP_TOKEN_EXPIRATION_SECONDS
                value: "${APP_TOKEN_EXPIRATION_SECONDS}"
              - name: APP_PAGINATION_DEFAULT_LIMIT
                value: ${APP_PAGINATION_DEFAULT_LIMIT}
              - name: APP_PAGINATION_MAX_LIMIT
                value: ${APP_PAGINATION_MAX_LIMIT}
              - name: APP_ACCEPT_X_RH_FAKE_IDENTITY
                value: ${APP_ACCEPT_X_RH_FAKE_IDENTITY}
              - name: APP_VALIDATE_API
                value: ${APP_VALIDATE_API}
              - name: APP_ENABLE_RBAC
                value: ${APP_ENABLE_RBAC}
              - name: APP_SECRET
                valueFrom:
                  secretKeyRef:
                    key: app_secret
                    name: app-secret
              - name: CLIENTS_RBAC_BASE_URL
                value: "${CLIENTS_RBAC_BASE_URL}"
              - name: CLIENTS_PENDO_BASE_URL
                value: "${CLIENTS_PENDO_BASE_URL}"
              - name: CLIENTS_PENDO_API_KEY
                valueFrom:
                  secretKeyRef:
                    key: integration-key
                    name: pendo-creds
                    optional: true
              - name: CLIENTS_PENDO_TRACK_EVENT_KEY
                valueFrom:
                  secretKeyRef:
                    key: track-event-secret
                    name: pendo-creds
                    optional: true
              - name: DATABASE_MAX_OPEN_CONNS
                value: "${DATABASE_MAX_OPEN_CONNS}"
              - name: APP_IDLE_TIMEOUT
                value: "${APP_IDLE_TIMEOUT}"
              - name: APP_READ_TIMEOUT
                value: "${APP_READ_TIMEOUT}"
              - name: APP_WRITE_TIMEOUT
                value: "${APP_WRITE_TIMEOUT}"
              - name: APP_SIZE_LIMIT_REQUEST_HEADER
                value: "${APP_SIZE_LIMIT_REQUEST_HEADER}"
              - name: APP_SIZE_LIMIT_REQUEST_BODY
                value: "${APP_SIZE_LIMIT_REQUEST_BODY}"
            resources:
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}
            volumes:
              - emptyDir: {}
                name: tmpdir
            volumeMounts:
              - mountPath: /tmp
                name: tmpdir

      # https://consoledot.pages.redhat.com/clowder/dev/providers/kafka.html
      # TODO Uncomment when kafka is needed or clean-up
      # kafkaTopics:
      #   - partitions: 3
      #     replicas: 3
      #     topicName: platform.${APP_NAME}.todo-created

      # https://consoledot.pages.redhat.com/clowder/dev/providers/cronjob.html
      jobs:
        - name: jwk-refresh
          schedule: "@hourly"
          concurrencyPolicy: Replace
          restartPolicy: Never
          suspend: ${{DB_JWK_REFRESH_SUSPEND}}
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            command:
              - /opt/bin/db-tool
              - jwk
              - refresh
            env:
              - name: CLOWDER_ENABLED
                value: "true"
              - name: LOGGING_LEVEL
                value: ${{LOGGING_LEVEL}}
              - name: LOGGING_LOCATION
                value: ${LOGGING_LOCATION}
              - name: APP_TOKEN_EXPIRATION_SECONDS
                value: "${APP_TOKEN_EXPIRATION_SECONDS}"
              - name: APP_ENABLE_RBAC
                value: ${APP_ENABLE_RBAC}
              - name: APP_SECRET
                valueFrom:
                  secretKeyRef:
                    key: app_secret
                    name: app-secret
              - name: CLIENTS_RBAC_BASE_URL
                value: "${CLIENTS_RBAC_BASE_URL}"
              - name: DATABASE_MAX_OPEN_CONNS
                value: "${DATABASE_MAX_OPEN_CONNS}"
            resources:
              limits:
                cpu: ${CPU_LIMIT}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}

      # https://consoledot.pages.redhat.com/clowder/dev/providers/database.html
      database:
        name: ${APP_NAME}
        version: 15

parameters:
  - name: ENV_NAME
    required: true
  - name: APP_NAME
    value: idmsvc
    description: |
      The internal application name that is used to
      compose the API path for its routes.
  - name: IMAGE
    value: quay.io/cloudservices/idmsvc-backend
  - name: IMAGE_TAG
    required: true
  - name: SERVICE_REPLICAS
    required: true
    description: |
      Minimum number of replicas to deploy for the API service component
  - name: CPU_LIMIT
    value: 500m
    description: |
      The resource limit for the cpu per pod
  - name: CPU_REQUESTS
    value: 100m
    description: |
      The resource request for the cpu per pod
  - name: MEMORY_LIMIT
    value: 1Gi
    description: |
      The resource limit for the memory per pod
  - name: MEMORY_REQUESTS
    value: 100Mi
    description: |
      The resource request for the memory per pod
  - name: LOGGING_LEVEL
    value: info
    description: |
      The log level for the deployment; valid values
      are "info", "warn", "error", "debug", "trace".
  - name: LOGGING_LOCATION
    value: "false"
    description: |
      Log source code locations of log statements.
  - name: APP_TOKEN_EXPIRATION_SECONDS
    value: "7200"
    description: |
      Indicate the token expiration duration expressed in
      seconds. By default set to 7200 seconds (2 hours).
  - name: APP_PAGINATION_DEFAULT_LIMIT
    value: "10"
    description: |
      The pagination default limit default to list domains
  - name: APP_PAGINATION_MAX_LIMIT
    value: "100"
    description: |
      The pagination max limit to list domains
  - name: APP_ACCEPT_X_RH_FAKE_IDENTITY
    value: "false"
    description: |
      It is used only for development to add middleware to
      process the x-rh-fake-identity header.
  - name: APP_VALIDATE_API
    value: "false"
    description: |
      It allows to validate API requests by using the
      service OpenAPI specification.
  - name: DB_JWK_REFRESH_SUSPEND
    value: "false"
    description: |
      A flag to suspend execution of 'db-tool jwk refresh' cron job.
  - name: APP_ENABLE_RBAC
    value: "true"
    description: |
      It allows to enable / disable RBAC middleware.
  - name: CLIENTS_RBAC_BASE_URL
    required: false
    description: |
      Point out to the rbac service base url
  - name: CLIENTS_PENDO_BASE_URL
    value: "https://api.pendo.io"
    required: false
    description: |
      Point out to the pendo service base url
  - name: DATABASE_MAX_OPEN_CONNS
    required: false
    description: |
      The maximum number of open connections to the database
  - name: APP_IDLE_TIMEOUT
    value: "5m"
    required: false
    description: |
      The idle timeout for the public API endpoints. Default 5m.
  - name: APP_READ_TIMEOUT
    value: "3s"
    required: false
    description: |
      The read timeout for the public API endpoints, which
      is the maximum time to read the request headers and
      body. Default 3s.
  - name: APP_WRITE_TIMEOUT
    value: "3s"
    required: false
    description: |
      The write timeout for the public API endpoints, which
      is the maximum time to write the response headers and
      body for a given request. Default 3s.
  - name: APP_SIZE_LIMIT_REQUEST_HEADER
    value: "32768"
    required: false
    description: |
      The maximum size for the request headers that receives
      the public API endpoints. Default 32KB.
  - name: APP_SIZE_LIMIT_REQUEST_BODY
    value: "131072"
    required: false
    description: |
      The maximum size for the request body that receives the
      public API endpoints. Default 128KB.
