// Code generated by mockery v2.16.0. DO NOT EDIT.

package repository

import (
	interactor "github.com/hmsidm/internal/interface/interactor"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	model "github.com/hmsidm/internal/domain/model"
)

// HostRepository is an autogenerated mock type for the HostRepository type
type HostRepository struct {
	mock.Mock
}

// MatchDomain provides a mock function with given fields: db, options
func (_m *HostRepository) MatchDomain(db *gorm.DB, options *interactor.HostConfOptions) (*model.Domain, error) {
	ret := _m.Called(db, options)

	var r0 *model.Domain
	if rf, ok := ret.Get(0).(func(*gorm.DB, *interactor.HostConfOptions) *model.Domain); ok {
		r0 = rf(db, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*gorm.DB, *interactor.HostConfOptions) error); ok {
		r1 = rf(db, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewHostRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewHostRepository creates a new instance of HostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHostRepository(t mockConstructorTestingTNewHostRepository) *HostRepository {
	mock := &HostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
