// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package public

const (
	X_rh_identityScopes = "x_rh_identity.Scopes"
)

// Defines values for CreateDomainDomainType.
const (
	CreateDomainDomainTypeIpa CreateDomainDomainType = "ipa"
)

// Defines values for CreateDomainResponseDomainType.
const (
	CreateDomainResponseDomainTypeIpa CreateDomainResponseDomainType = "ipa"
)

// CreateDomain A domain resource
type CreateDomain struct {
	// AutoEnrollmentEnabled Enable or disable host vm auto-enrollment for this domain
	AutoEnrollmentEnabled bool `json:"auto_enrollment_enabled"`

	// DomainName Domain name
	DomainName string `json:"domain_name"`

	// DomainType Type of this domain. Currently only ipa is supported.
	DomainType CreateDomainDomainType `json:"domain_type"`

	// Ipa Options for ipa domains
	Ipa CreateDomainIpa `json:"ipa"`
}

// CreateDomainDomainType Type of this domain. Currently only ipa is supported.
type CreateDomainDomainType string

// CreateDomainIpa Options for ipa domains
type CreateDomainIpa struct {
	// CaList A base64 representation of all the list of chain of certificates, including the server ca.
	CaList string `json:"ca_list"`

	// RealmName The realm name for the domain
	RealmName *string `json:"realm_name,omitempty"`

	// ServerList List of auto-enrollment enabled servers for this domain.
	ServerList *[]string `json:"server_list,omitempty"`
}

// CreateDomainResponse A domain resource
type CreateDomainResponse struct {
	// AutoEnrollmentEnabled Enable or disable host vm auto-enrollment for this domain
	AutoEnrollmentEnabled bool `json:"auto_enrollment_enabled"`

	// DomainName Domain name
	DomainName string `json:"domain_name"`

	// DomainType Type of this domain. Currently only ipa is supported.
	DomainType CreateDomainResponseDomainType `json:"domain_type"`

	// DomainUuid Internal id for this domain
	DomainUuid string `json:"domain_uuid"`

	// Ipa Options for ipa domains
	Ipa CreateDomainIpa `json:"ipa"`
}

// CreateDomainResponseDomainType Type of this domain. Currently only ipa is supported.
type CreateDomainResponseDomainType string

// Error General error schema
type Error struct {
	// Detail A human-readable explanation specific to this occurrence of the problem. This field’s value can be localized.
	Detail string `json:"detail"`

	// Id A unique identifier for this particular occurrence of the problem.
	Id string `json:"id"`

	// Status The HTTP status code applicable to this problem, expressed as a string value. This SHOULD be provided.
	Status *string `json:"status,omitempty"`
}

// ErrorResponse General error response returned by the hmsidm API
type ErrorResponse struct {
	// Errors Error objects provide additional information about problems encountered while performing an operation.
	Errors *[]Error `json:"errors,omitempty"`
}

// ListDomainsParams defines parameters for ListDomains.
type ListDomainsParams struct {
	// Offset pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// XRhIdentity Identity header for the request
	XRhIdentity []byte `json:"X-Rh-Identity"`

	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId string `json:"X-Rh-Insights-Request-Id"`
}

// CreateDomainParams defines parameters for CreateDomain.
type CreateDomainParams struct {
	// XRhIdentity Identity header for the request
	XRhIdentity []byte `json:"X-Rh-Identity"`

	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId string `json:"X-Rh-Insights-Request-Id"`
}

// DeleteDomainParams defines parameters for DeleteDomain.
type DeleteDomainParams struct {
	// XRhIdentity Identity header for the request
	XRhIdentity []byte `json:"X-Rh-Identity"`

	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId string `json:"X-Rh-Insights-Request-Id"`
}

// CreateDomainJSONRequestBody defines body for CreateDomain for application/vnd.api+json ContentType.
type CreateDomainJSONRequestBody = CreateDomain
