// Package metrics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package metrics

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/3RSwWrcMBD9FTHtoWVda9P0UBRyKKSUPZQWSk8hByGPbVFrJDRjs2Hxvxd517t0m1yM",
	"JM978+a9OYCLIUVCEgZzgIycIjEul+8o2bvl6CIJkpSj4F50GqynOzVhZh/pfltv6093yvU2M8r9KO2H",
	"z6WWXY/BltPbjC0YeKMv/fTxL+sHKxbmea6gQXbZJ/GRwKz91SoKSskJVDgXnDm8gjoWKsvqohgqkOeE",
	"YIAle+qOXT218X+er3sb0oAqturLz51qkH1HqvWZRdmUcrSuV5YaNbKnTnVxsNQpFuv+qHeTT5g36Pq4",
	"6WIOGxepHUYk2bgBLdnsei/oZMz4vojCHPhH+wvz5F2R14skNlq7SBwHrDM2vZXaxaBt8to3gSenp5uC",
	"9TIUyI5Y8hiQxJYJimio4JQQGCgZ3cBcQUxINnkwcFtv61uoIFnpF0d1+XQoL7hBTYqeRElUuE+RUUmP",
	"KpzMbmNe7v5KxDltWPrm5XXXgIFvKOt+Vf+u3cft9rWNOdfpFbusxBiCzc9LZtfKikG2YzCPsL48LaEz",
	"5uINmMfrUX8zLvM84IRDTOGofswDGNAryfx0Jr7GX3uAJ+ugArKhRHUhmf8GAAD//4WuiKmBAwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
