// Package metrics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package metrics

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/3RSQWvcPBD9K2K+79CyrrVpeigKORRSSg6lhdJTyEHIY1vUGgnNeNmw+L8Xade7dNtc",
	"jCTPe/PmvTmAiyFFQhIGc4CMnCIx1stXlOxdPbpIgiTlKLgXnSbr6U7tMLOPdL9tt+2HO+VGmxnlfpb+",
	"3cdSy27EYMvp/4w9GPhPX/rp41/WD1YsLMvSQIfssk/iI4FZ+6tVFJSSE6hwVpw5vII6FirL6qIYGpCX",
	"hGCAJXsajl099fFvns97G9KEKvbq0/dH1SH7gVTvM4uyKeVo3agsdWpmT4Ma4mRpUCzW/VJvdj5h3qAb",
	"42aIOWxcpH6akWTjJrRksxu9oJM549siCnPgb/0PzDvvirxRJLHR2kXiOGGbsRuttC4GbZPXY2DfBb27",
	"KVgvU4E8EkueA5LYMkERDQ2cEgIDJaMbWBqICckmDwZu2217Cw0kK2N1VJfPgPIPN6hL0ZMoiQr3KTIq",
	"GVGFk9l9zPXur0Sc04baN9fXxw4MfEFZ96v5c+3eb7evbcy5Tq/YuhJzCDa/1MyulRWD7MBgnmB9ea6h",
	"M+biDZin61F/MtZ5HnCHU0zhqH7OExjQK8nyfCa+xl97gCfroAGyoUR1IVl+BwAA///yEr6DgQMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
