// Package metrics provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package metrics

// Data Metrics schema as text/plain
type Data = string
