// Code generated by mockery v2.16.0. DO NOT EDIT.

package presenter

import (
	model "github.com/hmsidm/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	public "github.com/hmsidm/internal/api/public"
)

// DomainPresenter is an autogenerated mock type for the DomainPresenter type
type DomainPresenter struct {
	mock.Mock
}

// Create provides a mock function with given fields: domain
func (_m *DomainPresenter) Create(domain *model.Domain) (*public.CreateDomainResponse, error) {
	ret := _m.Called(domain)

	var r0 *public.CreateDomainResponse
	if rf, ok := ret.Get(0).(func(*model.Domain) *public.CreateDomainResponse); ok {
		r0 = rf(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*public.CreateDomainResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Domain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: domain
func (_m *DomainPresenter) Get(domain *model.Domain) (*public.ReadDomainResponse, error) {
	ret := _m.Called(domain)

	var r0 *public.ReadDomainResponse
	if rf, ok := ret.Get(0).(func(*model.Domain) *public.ReadDomainResponse); ok {
		r0 = rf(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*public.ReadDomainResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Domain) error); ok {
		r1 = rf(domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: prefix, offset, count, data
func (_m *DomainPresenter) List(prefix string, offset int64, count int32, data []model.Domain) (*public.ListDomainsResponse, error) {
	ret := _m.Called(prefix, offset, count, data)

	var r0 *public.ListDomainsResponse
	if rf, ok := ret.Get(0).(func(string, int64, int32, []model.Domain) *public.ListDomainsResponse); ok {
		r0 = rf(prefix, offset, count, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*public.ListDomainsResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64, int32, []model.Domain) error); ok {
		r1 = rf(prefix, offset, count, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDomainPresenter interface {
	mock.TestingT
	Cleanup(func())
}

// NewDomainPresenter creates a new instance of DomainPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDomainPresenter(t mockConstructorTestingTNewDomainPresenter) *DomainPresenter {
	mock := &DomainPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
