{
 "title": "Directory and Domain Services",
 "description": "Grafana observatory dashboard for Directory and Domain Services",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Internal Server error ratio",
   "type": "timeseries",
   "description": "Ratio of HTTP response codes that are not 5xx",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1.00 - (sum(rate(api_3scale_gateway_api_status{exported_service=\"idmsvc\", status=\"5xx\"}[28d])) / sum(rate(api_3scale_gateway_api_status{exported_service=\"idmsvc\"}[28d])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency rate <=2000ms",
   "type": "timeseries",
   "description": "Proportion of requests with less than <=2000ms against all requests on idmsvc API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_time_bucket{le=\"2000.0\", exported_service=\"idmsvc\"}[28d]))/sum(rate(api_3scale_gateway_api_time_bucket{le=\"+Inf\", exported_service=\"idmsvc\"}[28d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency from API Gateway",
   "type": "heatmap",
   "description": "Latency of requests over time measured from api_3scale metrics.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_time_bucket{exported_service=\"idmsvc\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency from API service",
   "type": "heatmap",
   "description": "Latency of requests over time measured from idmsvc_duration metrics.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(idmsvc_http_request_duration_seconds_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "description": "Show the availability of the service along the time.  A value different of 1 is bad, the graph along the time give us the time window when the availability was lost.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "up{namespace=\"idmsvc-stage\", service=\"idmsvc-backend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}