// Code generated by mockery v2.53.3. DO NOT EDIT.

package rbac

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Rbac is an autogenerated mock type for the Rbac type
type Rbac struct {
	mock.Mock
}

// IsAllowed provides a mock function with given fields: ctx, xrhid, permission
func (_m *Rbac) IsAllowed(ctx context.Context, xrhid string, permission string) (bool, error) {
	ret := _m.Called(ctx, xrhid, permission)

	if len(ret) == 0 {
		panic("no return value specified for IsAllowed")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, xrhid, permission)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, xrhid, permission)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, xrhid, permission)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRbac creates a new instance of Rbac. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRbac(t interface {
	mock.TestingT
	Cleanup(func())
}) *Rbac {
	mock := &Rbac{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
