@startuml architecture

() "Kafka Consumers" as kafka_consumer


() "Kafka Producers" as kafka_producer

() "Http Handlers" as http_requests

()"Http Clients" as http_clients

()"Database" as database

[Service] as service

http_requests - service:
service - http_clients: third party services
service - kafka_producer: produce event topics
kafka_consumer - service: kafka handler
service - database: crud

@enduml
