@startuml
hide circle
skinparam linetype ortho

entity "**domains**" {
  + ""id"": //serial [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  ""deleted_at"": //timestamp with time zone //
  *""org_id"": //character varying(255) //
  *""domain_uuid"": //uuid //
  *""domain_name"": //character varying(253) //
  *""domain_description"": //character varying(255) //
  *""domain_type"": //integer //
  *""auto_enrollment_enabled"": //boolean //
}

entity "**ipa_certs**" {
  + ""id"": //serial [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  ""deleted_at"": //timestamp with time zone //
  ""ipa_id"": //integer [FK]//
  *""issuer"": //character varying(255) //
  *""nickname"": //character varying(255) //
  *""not_valid_after"": //timestamp with time zone //
  *""not_valid_before"": //timestamp with time zone //
  *""serial_number"": //character varying(255) //
  *""subject"": //character varying(255) //
}

entity "**ipa_servers**" {
  + ""id"": //serial [PK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  ""deleted_at"": //timestamp with time zone //
  ""ipa_id"": //integer [FK]//
}

entity "**ipas**" {
  + ""id"": //serial [PK][FK]//
  --
  ""created_at"": //timestamp with time zone //
  ""updated_at"": //timestamp with time zone //
  ""deleted_at"": //timestamp with time zone //
  *""realm_name"": //character varying(253) //
}

entity "**schema_migrations**" {
  + ""version"": //bigint [PK]//
  --
  *""dirty"": //boolean //
}

"**ipa_certs**"   }--  "**ipas**"

"**ipa_servers**"   }--  "**ipas**"

"**ipas**"  ||-||  "**domains**"
@enduml
