// Package public provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package public

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	X_rh_identityScopes               = "x_rh_identity.Scopes"
	X_rh_idm_registration_tokenScopes = "x_rh_idm_registration_token.Scopes"
)

// Defines values for DomainType.
const (
	RhelIdm DomainType = "rhel-idm"
)

// CaCertBundle A string of concatenated, PEM-encoded X.509 certificates
type CaCertBundle = string

// Certificate defines model for Certificate.
type Certificate struct {
	Issuer       string    `json:"issuer"`
	Nickname     string    `json:"nickname"`
	NotAfter     time.Time `json:"not_after"`
	NotBefore    time.Time `json:"not_before"`
	Pem          string    `json:"pem"`
	SerialNumber string    `json:"serial_number"`
	Subject      string    `json:"subject"`
}

// Domain A domain resource
type Domain struct {
	// AutoEnrollmentEnabled Enable or disable host vm auto-enrollment for this domain
	AutoEnrollmentEnabled *bool `json:"auto_enrollment_enabled,omitempty"`

	// Description Human readable description abou the domain.
	Description *string `json:"description,omitempty"`

	// DomainId A domain id
	DomainId *DomainId `json:"domain_id,omitempty"`

	// DomainName A name of a domain (all lower-case). The domain name can only be set during initial registration and not be modified by updates.
	DomainName DomainName `json:"domain_name"`

	// DomainType Type of domain (currently only rhel-idm)
	DomainType DomainType `json:"domain_type"`

	// RhelIdm Options for ipa domains
	RhelIdm *DomainIpa `json:"rhel-idm,omitempty"`

	// Title Title to describe the domain.
	Title *string `json:"title,omitempty"`
}

// DomainId A domain id
type DomainId = openapi_types.UUID

// DomainIpa Options for ipa domains
type DomainIpa struct {
	// AutomountLocations List of automount locations for AutoFS
	AutomountLocations *[]string `json:"automount_locations,omitempty"`

	// CaCerts A base64 representation of all the list of chain of certificates, including the server ca.
	CaCerts []Certificate `json:"ca_certs"`

	// Locations List of DNS locations
	Locations []Location `json:"locations"`

	// RealmDomains List of realm associated to the IPA domain.
	RealmDomains []DomainName `json:"realm_domains"`

	// RealmName A Kerberos realm name (usually all upper-case domain name). The realm can only be set during initial registration and not be modified by updates.
	RealmName RealmName `json:"realm_name"`

	// Servers List of auto-enrollment enabled servers for this domain.
	Servers []DomainIpaServer `json:"servers"`
}

// DomainIpaServer Server schema for an entry into the Ipa domain type.
type DomainIpaServer struct {
	CaServer bool `json:"ca_server"`

	// Fqdn A host's Fully Qualified Domain Name (all lower-case).
	Fqdn                Fqdn `json:"fqdn"`
	HccEnrollmentServer bool `json:"hcc_enrollment_server"`
	HccUpdateServer     bool `json:"hcc_update_server"`

	// Location A location identifier (lower-case DNS label)
	Location     *LocationName `json:"location,omitempty"`
	PkinitServer bool          `json:"pkinit_server"`

	// SubscriptionManagerId A Red Hat Subcription Manager ID of a RHEL host.
	SubscriptionManagerId *SubscriptionManagerId `json:"subscription_manager_id,omitempty"`
}

// DomainName A name of a domain (all lower-case). The domain name can only be set during initial registration and not be modified by updates.
type DomainName = string

// DomainRegToken A domain registration response
type DomainRegToken struct {
	// DomainId A domain id
	DomainId DomainId `json:"domain_id"`

	// DomainToken A domain registration token string
	DomainToken string `json:"domain_token"`

	// DomainType Type of domain (currently only rhel-idm)
	DomainType DomainType `json:"domain_type"`

	// Expiration Expiration time stamp (Unix timestamp)
	Expiration int `json:"expiration"`
}

// DomainRegTokenRequest A domain registration request
type DomainRegTokenRequest struct {
	// DomainType Type of domain (currently only rhel-idm)
	DomainType DomainType `json:"domain_type"`
}

// DomainRegisterResponse A domain resource
type DomainRegisterResponse = Domain

// DomainResponse A domain resource
type DomainResponse = Domain

// DomainType Type of domain (currently only rhel-idm)
type DomainType string

// DomainUpdateResponse A domain resource
type DomainUpdateResponse = Domain

// ErrorInfo defines model for ErrorInfo.
type ErrorInfo struct {
	// Code an application-specific error code
	Code *string `json:"code,omitempty"`

	// Detail A detailed explanation of the error, e.g. traceback.
	Detail *string `json:"detail,omitempty"`

	// Id a unique identifier for this particular occurrence of the problem.
	Id string `json:"id"`

	// Status The HTTP status code for the error.
	Status string `json:"status"`

	// Title The human-readable HTTP status text for the error.
	Title string `json:"title"`
}

// Errors General error response returned by the idmsvc API
type Errors struct {
	// Errors Error objects provide additional information about problems encountered while performing an operation.
	Errors *[]ErrorInfo `json:"errors,omitempty"`
}

// Fqdn A host's Fully Qualified Domain Name (all lower-case).
type Fqdn = string

// HostConf Represent the request payload for the /host-conf/:inventory_id/:fqdn endpoint.
type HostConf struct {
	// DomainId A domain id
	DomainId *DomainId `json:"domain_id,omitempty"`

	// DomainName A name of a domain (all lower-case). The domain name can only be set during initial registration and not be modified by updates.
	DomainName *DomainName `json:"domain_name,omitempty"`

	// DomainType Type of domain (currently only rhel-idm)
	DomainType *DomainType `json:"domain_type,omitempty"`
}

// HostConfIpa Options for ipa domains
type HostConfIpa struct {
	// AutomountLocation Automount location name for ipa-client-automount
	AutomountLocation *string `json:"automount_location,omitempty"`

	// Cabundle A string of concatenated, PEM-encoded X.509 certificates
	Cabundle CaCertBundle `json:"cabundle"`

	// EnrollmentServers List of auto-enrollment enabled servers for this domain.
	EnrollmentServers []HostConfIpaServer `json:"enrollment_servers"`

	// IpaClientInstallArgs List of additional arguments for ipa-client-install
	IpaClientInstallArgs *[]string `json:"ipa_client_install_args,omitempty"`

	// RealmName A Kerberos realm name (usually all upper-case domain name). The realm can only be set during initial registration and not be modified by updates.
	RealmName RealmName `json:"realm_name"`
}

// HostConfIpaServer Auto-enrollment enabled server for this domain.
type HostConfIpaServer struct {
	// Fqdn A host's Fully Qualified Domain Name (all lower-case).
	Fqdn Fqdn `json:"fqdn"`

	// Location A location identifier (lower-case DNS label)
	Location *LocationName `json:"location,omitempty"`
}

// HostConfResponseSchema The response for the action to retrieve the host vm information when it is being enrolled. This action is taken from the host vm.
type HostConfResponseSchema struct {
	// AutoEnrollmentEnabled Enable or disable host vm auto-enrollment for this domain
	AutoEnrollmentEnabled bool `json:"auto_enrollment_enabled"`

	// DomainId A domain id
	DomainId DomainId `json:"domain_id"`

	// DomainName A name of a domain (all lower-case). The domain name can only be set during initial registration and not be modified by updates.
	DomainName DomainName `json:"domain_name"`

	// DomainType Type of domain (currently only rhel-idm)
	DomainType DomainType `json:"domain_type"`

	// RhelIdm Options for ipa domains
	RhelIdm HostConfIpa `json:"rhel-idm"`

	// Token A serialized JWS token or JWT to authenticate a host registration request.
	Token *HostToken `json:"token,omitempty"`
}

// HostId A Host-Based Inventory ID of a host.
type HostId = openapi_types.UUID

// HostToken A serialized JWS token or JWT to authenticate a host registration request.
type HostToken = string

// ListDomainsData The data listed for the domains.
type ListDomainsData struct {
	AutoEnrollmentEnabled bool `json:"auto_enrollment_enabled"`

	// Description Human-readable description of the domain entry.
	Description string `json:"description"`

	// DomainId A domain id
	DomainId DomainId `json:"domain_id"`

	// DomainName A name of a domain (all lower-case). The domain name can only be set during initial registration and not be modified by updates.
	DomainName DomainName `json:"domain_name"`

	// DomainType Type of domain (currently only rhel-idm)
	DomainType DomainType `json:"domain_type"`

	// Title Human-friendly title for the domain entry.
	Title string `json:"title"`
}

// ListDomainsResponseSchema Represent a paginated result for a list of domains
type ListDomainsResponseSchema struct {
	// Data The content for this page.
	Data []ListDomainsData `json:"data"`

	// Links Represent the navigation links for the data paginated.
	Links PaginationLinks `json:"links"`

	// Meta Metadata for the paginated responses.
	Meta PaginationMeta `json:"meta"`
}

// Location RHEL IdM server location
type Location struct {
	Description *string `json:"description,omitempty"`

	// Name A location identifier (lower-case DNS label)
	Name LocationName `json:"name"`
}

// LocationName A location identifier (lower-case DNS label)
type LocationName = string

// PaginationLinks Represent the navigation links for the data paginated.
type PaginationLinks struct {
	// First Reference to the first page of the request.
	First *string `json:"first,omitempty"`

	// Last Reference to the last page of the request.
	Last *string `json:"last,omitempty"`

	// Next Reference to the next page of the request.
	Next *string `json:"next,omitempty"`

	// Previous Reference to the previous page of the request.
	Previous *string `json:"previous,omitempty"`
}

// PaginationMeta Metadata for the paginated responses.
type PaginationMeta struct {
	// Count total records in the collection.
	Count int64 `json:"count"`

	// Limit Number of items per page.
	Limit int `json:"limit"`

	// Offset Initial record of the page.
	Offset int `json:"offset"`
}

// RealmName A Kerberos realm name (usually all upper-case domain name). The realm can only be set during initial registration and not be modified by updates.
type RealmName = string

// RegisterDomainRequest A domain resource
type RegisterDomainRequest = Domain

// SigningKeysResponse Serialized JWKs with revocation information
type SigningKeysResponse struct {
	// Keys An array of serialized JSON Web Keys (JWK strings)
	Keys []string `json:"keys"`

	// RevokedKids An array of revoked key identifiers (JWK kid)
	RevokedKids *[]string `json:"revoked_kids,omitempty"`
}

// SubscriptionManagerId A Red Hat Subcription Manager ID of a RHEL host.
type SubscriptionManagerId = openapi_types.UUID

// UpdateDomainAgentRequest A domain resource
type UpdateDomainAgentRequest struct {
	// DomainName A name of a domain (all lower-case). The domain name can only be set during initial registration and not be modified by updates.
	DomainName DomainName `json:"domain_name"`

	// DomainType Type of domain (currently only rhel-idm)
	DomainType DomainType `json:"domain_type"`

	// RhelIdm Options for ipa domains
	RhelIdm DomainIpa `json:"rhel-idm"`
}

// UpdateDomainUserRequest A domain resource
type UpdateDomainUserRequest struct {
	// AutoEnrollmentEnabled Enable or disable host vm auto-enrollment for this domain
	AutoEnrollmentEnabled *bool `json:"auto_enrollment_enabled,omitempty"`

	// Description Human readable description abou the domain.
	Description *string `json:"description,omitempty"`

	// Title Title to describe the domain.
	Title *string `json:"title,omitempty"`
}

// DomainIdParam A domain id
type DomainIdParam = DomainId

// XRhIdmRegistrationTokenHeader defines model for XRhIdmRegistrationTokenHeader.
type XRhIdmRegistrationTokenHeader = string

// XRhIdmVersionHeader defines model for XRhIdmVersionHeader.
type XRhIdmVersionHeader = string

// XRhInsightsRequestIdHeader defines model for XRhInsightsRequestIdHeader.
type XRhInsightsRequestIdHeader = string

// DomainRegTokenResponse A domain registration response
type DomainRegTokenResponse = DomainRegToken

// ErrorResponse General error response returned by the idmsvc API
type ErrorResponse = Errors

// HostConfResponse The response for the action to retrieve the host vm information when it is being enrolled. This action is taken from the host vm.
type HostConfResponse = HostConfResponseSchema

// ListDomainsResponse Represent a paginated result for a list of domains
type ListDomainsResponse = ListDomainsResponseSchema

// ReadDomainResponse A domain resource
type ReadDomainResponse = DomainResponse

// ReadKeysResponse Serialized JWKs with revocation information
type ReadKeysResponse = SigningKeysResponse

// RegisterDomainResponse TODO
type RegisterDomainResponse = DomainRegisterResponse

// UpdateDomainAgentResponse TODO
type UpdateDomainAgentResponse = DomainUpdateResponse

// UpdateDomainUserResponse A domain resource
type UpdateDomainUserResponse = DomainResponse

// ListDomainsParams defines parameters for ListDomains.
type ListDomainsParams struct {
	// Offset pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Number of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// RegisterDomainParams defines parameters for RegisterDomain.
type RegisterDomainParams struct {
	// XRhIdmRegistrationToken One-time password to authenticate domain registration with ipa-hcc command.
	XRhIdmRegistrationToken XRhIdmRegistrationTokenHeader `json:"X-Rh-Idm-Registration-Token"`

	// XRhIdmVersion ipa-hcc agent version
	XRhIdmVersion XRhIdmVersionHeader `json:"X-Rh-Idm-Version"`

	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// CreateDomainTokenParams defines parameters for CreateDomainToken.
type CreateDomainTokenParams struct {
	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// DeleteDomainParams defines parameters for DeleteDomain.
type DeleteDomainParams struct {
	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// ReadDomainParams defines parameters for ReadDomain.
type ReadDomainParams struct {
	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// UpdateDomainUserParams defines parameters for UpdateDomainUser.
type UpdateDomainUserParams struct {
	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// UpdateDomainAgentParams defines parameters for UpdateDomainAgent.
type UpdateDomainAgentParams struct {
	// XRhIdmVersion ipa-hcc agent version
	XRhIdmVersion XRhIdmVersionHeader `json:"X-Rh-Idm-Version"`

	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// HostConfParams defines parameters for HostConf.
type HostConfParams struct {
	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// GetSigningKeysParams defines parameters for GetSigningKeys.
type GetSigningKeysParams struct {
	// XRhInsightsRequestId Request id for distributed tracing.
	XRhInsightsRequestId *XRhInsightsRequestIdHeader `json:"X-Rh-Insights-Request-Id,omitempty"`
}

// RegisterDomainJSONRequestBody defines body for RegisterDomain for application/json ContentType.
type RegisterDomainJSONRequestBody = RegisterDomainRequest

// CreateDomainTokenJSONRequestBody defines body for CreateDomainToken for application/json ContentType.
type CreateDomainTokenJSONRequestBody = DomainRegTokenRequest

// UpdateDomainUserJSONRequestBody defines body for UpdateDomainUser for application/json ContentType.
type UpdateDomainUserJSONRequestBody = UpdateDomainUserRequest

// UpdateDomainAgentJSONRequestBody defines body for UpdateDomainAgent for application/json ContentType.
type UpdateDomainAgentJSONRequestBody = UpdateDomainAgentRequest

// HostConfJSONRequestBody defines body for HostConf for application/json ContentType.
type HostConfJSONRequestBody = HostConf

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListDomains request
	ListDomains(ctx context.Context, params *ListDomainsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RegisterDomainWithBody request with any body
	RegisterDomainWithBody(ctx context.Context, params *RegisterDomainParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RegisterDomain(ctx context.Context, params *RegisterDomainParams, body RegisterDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDomainTokenWithBody request with any body
	CreateDomainTokenWithBody(ctx context.Context, params *CreateDomainTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDomainToken(ctx context.Context, params *CreateDomainTokenParams, body CreateDomainTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDomain request
	DeleteDomain(ctx context.Context, uuid DomainIdParam, params *DeleteDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReadDomain request
	ReadDomain(ctx context.Context, uuid DomainIdParam, params *ReadDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDomainUserWithBody request with any body
	UpdateDomainUserWithBody(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateDomainUser(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, body UpdateDomainUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDomainAgentWithBody request with any body
	UpdateDomainAgentWithBody(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateDomainAgent(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, body UpdateDomainAgentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HostConfWithBody request with any body
	HostConfWithBody(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	HostConf(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, body HostConfJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSigningKeys request
	GetSigningKeys(ctx context.Context, params *GetSigningKeysParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListDomains(ctx context.Context, params *ListDomainsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDomainsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterDomainWithBody(ctx context.Context, params *RegisterDomainParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDomainRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterDomain(ctx context.Context, params *RegisterDomainParams, body RegisterDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterDomainRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDomainTokenWithBody(ctx context.Context, params *CreateDomainTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDomainTokenRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDomainToken(ctx context.Context, params *CreateDomainTokenParams, body CreateDomainTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDomainTokenRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDomain(ctx context.Context, uuid DomainIdParam, params *DeleteDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDomainRequest(c.Server, uuid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReadDomain(ctx context.Context, uuid DomainIdParam, params *ReadDomainParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReadDomainRequest(c.Server, uuid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDomainUserWithBody(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDomainUserRequestWithBody(c.Server, uuid, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDomainUser(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, body UpdateDomainUserJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDomainUserRequest(c.Server, uuid, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDomainAgentWithBody(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDomainAgentRequestWithBody(c.Server, uuid, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDomainAgent(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, body UpdateDomainAgentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDomainAgentRequest(c.Server, uuid, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HostConfWithBody(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHostConfRequestWithBody(c.Server, inventoryId, fqdn, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HostConf(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, body HostConfJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHostConfRequest(c.Server, inventoryId, fqdn, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSigningKeys(ctx context.Context, params *GetSigningKeysParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSigningKeysRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDomainsRequest generates requests for ListDomains
func NewListDomainsRequest(server string, params *ListDomainsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XRhInsightsRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam0)
		}

	}

	return req, nil
}

// NewRegisterDomainRequest calls the generic RegisterDomain builder with application/json body
func NewRegisterDomainRequest(server string, params *RegisterDomainParams, body RegisterDomainJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterDomainRequestWithBody(server, params, "application/json", bodyReader)
}

// NewRegisterDomainRequestWithBody generates requests for RegisterDomain with any type of body
func NewRegisterDomainRequestWithBody(server string, params *RegisterDomainParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Idm-Registration-Token", runtime.ParamLocationHeader, params.XRhIdmRegistrationToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Rh-Idm-Registration-Token", headerParam0)

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Idm-Version", runtime.ParamLocationHeader, params.XRhIdmVersion)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Rh-Idm-Version", headerParam1)

		if params.XRhInsightsRequestId != nil {
			var headerParam2 string

			headerParam2, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam2)
		}

	}

	return req, nil
}

// NewCreateDomainTokenRequest calls the generic CreateDomainToken builder with application/json body
func NewCreateDomainTokenRequest(server string, params *CreateDomainTokenParams, body CreateDomainTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDomainTokenRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateDomainTokenRequestWithBody generates requests for CreateDomainToken with any type of body
func NewCreateDomainTokenRequestWithBody(server string, params *CreateDomainTokenParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRhInsightsRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam0)
		}

	}

	return req, nil
}

// NewDeleteDomainRequest generates requests for DeleteDomain
func NewDeleteDomainRequest(server string, uuid DomainIdParam, params *DeleteDomainParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XRhInsightsRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam0)
		}

	}

	return req, nil
}

// NewReadDomainRequest generates requests for ReadDomain
func NewReadDomainRequest(server string, uuid DomainIdParam, params *ReadDomainParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XRhInsightsRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam0)
		}

	}

	return req, nil
}

// NewUpdateDomainUserRequest calls the generic UpdateDomainUser builder with application/json body
func NewUpdateDomainUserRequest(server string, uuid DomainIdParam, params *UpdateDomainUserParams, body UpdateDomainUserJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDomainUserRequestWithBody(server, uuid, params, "application/json", bodyReader)
}

// NewUpdateDomainUserRequestWithBody generates requests for UpdateDomainUser with any type of body
func NewUpdateDomainUserRequestWithBody(server string, uuid DomainIdParam, params *UpdateDomainUserParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRhInsightsRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam0)
		}

	}

	return req, nil
}

// NewUpdateDomainAgentRequest calls the generic UpdateDomainAgent builder with application/json body
func NewUpdateDomainAgentRequest(server string, uuid DomainIdParam, params *UpdateDomainAgentParams, body UpdateDomainAgentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDomainAgentRequestWithBody(server, uuid, params, "application/json", bodyReader)
}

// NewUpdateDomainAgentRequestWithBody generates requests for UpdateDomainAgent with any type of body
func NewUpdateDomainAgentRequestWithBody(server string, uuid DomainIdParam, params *UpdateDomainAgentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Idm-Version", runtime.ParamLocationHeader, params.XRhIdmVersion)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Rh-Idm-Version", headerParam0)

		if params.XRhInsightsRequestId != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam1)
		}

	}

	return req, nil
}

// NewHostConfRequest calls the generic HostConf builder with application/json body
func NewHostConfRequest(server string, inventoryId HostId, fqdn Fqdn, params *HostConfParams, body HostConfJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHostConfRequestWithBody(server, inventoryId, fqdn, params, "application/json", bodyReader)
}

// NewHostConfRequestWithBody generates requests for HostConf with any type of body
func NewHostConfRequestWithBody(server string, inventoryId HostId, fqdn Fqdn, params *HostConfParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "inventory_id", runtime.ParamLocationPath, inventoryId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "fqdn", runtime.ParamLocationPath, fqdn)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/host-conf/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XRhInsightsRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam0)
		}

	}

	return req, nil
}

// NewGetSigningKeysRequest generates requests for GetSigningKeys
func NewGetSigningKeysRequest(server string, params *GetSigningKeysParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/signing_keys")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XRhInsightsRequestId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Rh-Insights-Request-Id", runtime.ParamLocationHeader, *params.XRhInsightsRequestId)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Rh-Insights-Request-Id", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListDomainsWithResponse request
	ListDomainsWithResponse(ctx context.Context, params *ListDomainsParams, reqEditors ...RequestEditorFn) (*ListDomainsResponse, error)

	// RegisterDomainWithBodyWithResponse request with any body
	RegisterDomainWithBodyWithResponse(ctx context.Context, params *RegisterDomainParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDomainResponse, error)

	RegisterDomainWithResponse(ctx context.Context, params *RegisterDomainParams, body RegisterDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDomainResponse, error)

	// CreateDomainTokenWithBodyWithResponse request with any body
	CreateDomainTokenWithBodyWithResponse(ctx context.Context, params *CreateDomainTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDomainTokenOutput, error)

	CreateDomainTokenWithResponse(ctx context.Context, params *CreateDomainTokenParams, body CreateDomainTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDomainTokenOutput, error)

	// DeleteDomainWithResponse request
	DeleteDomainWithResponse(ctx context.Context, uuid DomainIdParam, params *DeleteDomainParams, reqEditors ...RequestEditorFn) (*DeleteDomainOutput, error)

	// ReadDomainWithResponse request
	ReadDomainWithResponse(ctx context.Context, uuid DomainIdParam, params *ReadDomainParams, reqEditors ...RequestEditorFn) (*ReadDomainResponse, error)

	// UpdateDomainUserWithBodyWithResponse request with any body
	UpdateDomainUserWithBodyWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDomainUserResponse, error)

	UpdateDomainUserWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, body UpdateDomainUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDomainUserResponse, error)

	// UpdateDomainAgentWithBodyWithResponse request with any body
	UpdateDomainAgentWithBodyWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDomainAgentResponse, error)

	UpdateDomainAgentWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, body UpdateDomainAgentJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDomainAgentResponse, error)

	// HostConfWithBodyWithResponse request with any body
	HostConfWithBodyWithResponse(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HostConfResponse, error)

	HostConfWithResponse(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, body HostConfJSONRequestBody, reqEditors ...RequestEditorFn) (*HostConfResponse, error)

	// GetSigningKeysWithResponse request
	GetSigningKeysWithResponse(ctx context.Context, params *GetSigningKeysParams, reqEditors ...RequestEditorFn) (*GetSigningKeysResponse, error)
}

type ListDomainsOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListDomainsResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListDomainsOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDomainsOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RegisterDomainOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RegisterDomainResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RegisterDomainOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterDomainOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDomainTokenOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *DomainRegTokenResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateDomainTokenOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDomainTokenOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteDomainOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteDomainOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDomainOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReadDomainOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReadDomainResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReadDomainOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReadDomainOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateDomainUserOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UpdateDomainUserResponse
	JSON400      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateDomainUserOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDomainUserOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateDomainAgentOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *UpdateDomainAgentResponse
	JSON400      *ErrorResponse
	JSON403      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateDomainAgentOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDomainAgentOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HostConfOutput struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HostConfResponse
}

// Status returns HTTPResponse.Status
func (r HostConfOutput) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HostConfOutput) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSigningKeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReadKeysResponse
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetSigningKeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSigningKeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListDomainsWithResponse request returning *ListDomainsResponse
func (c *ClientWithResponses) ListDomainsWithResponse(ctx context.Context, params *ListDomainsParams, reqEditors ...RequestEditorFn) (*ListDomainsOutput, error) {
	rsp, err := c.ListDomains(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDomainsResponse(rsp)
}

// RegisterDomainWithBodyWithResponse request with arbitrary body returning *RegisterDomainResponse
func (c *ClientWithResponses) RegisterDomainWithBodyWithResponse(ctx context.Context, params *RegisterDomainParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterDomainOutput, error) {
	rsp, err := c.RegisterDomainWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDomainResponse(rsp)
}

func (c *ClientWithResponses) RegisterDomainWithResponse(ctx context.Context, params *RegisterDomainParams, body RegisterDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterDomainOutput, error) {
	rsp, err := c.RegisterDomain(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterDomainResponse(rsp)
}

// CreateDomainTokenWithBodyWithResponse request with arbitrary body returning *CreateDomainTokenResponse
func (c *ClientWithResponses) CreateDomainTokenWithBodyWithResponse(ctx context.Context, params *CreateDomainTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDomainTokenOutput, error) {
	rsp, err := c.CreateDomainTokenWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDomainTokenResponse(rsp)
}

func (c *ClientWithResponses) CreateDomainTokenWithResponse(ctx context.Context, params *CreateDomainTokenParams, body CreateDomainTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDomainTokenOutput, error) {
	rsp, err := c.CreateDomainToken(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDomainTokenResponse(rsp)
}

// DeleteDomainWithResponse request returning *DeleteDomainResponse
func (c *ClientWithResponses) DeleteDomainWithResponse(ctx context.Context, uuid DomainIdParam, params *DeleteDomainParams, reqEditors ...RequestEditorFn) (*DeleteDomainOutput, error) {
	rsp, err := c.DeleteDomain(ctx, uuid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDomainResponse(rsp)
}

// ReadDomainWithResponse request returning *ReadDomainResponse
func (c *ClientWithResponses) ReadDomainWithResponse(ctx context.Context, uuid DomainIdParam, params *ReadDomainParams, reqEditors ...RequestEditorFn) (*ReadDomainOutput, error) {
	rsp, err := c.ReadDomain(ctx, uuid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReadDomainResponse(rsp)
}

// UpdateDomainUserWithBodyWithResponse request with arbitrary body returning *UpdateDomainUserResponse
func (c *ClientWithResponses) UpdateDomainUserWithBodyWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDomainUserOutput, error) {
	rsp, err := c.UpdateDomainUserWithBody(ctx, uuid, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDomainUserResponse(rsp)
}

func (c *ClientWithResponses) UpdateDomainUserWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainUserParams, body UpdateDomainUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDomainUserOutput, error) {
	rsp, err := c.UpdateDomainUser(ctx, uuid, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDomainUserResponse(rsp)
}

// UpdateDomainAgentWithBodyWithResponse request with arbitrary body returning *UpdateDomainAgentResponse
func (c *ClientWithResponses) UpdateDomainAgentWithBodyWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDomainAgentOutput, error) {
	rsp, err := c.UpdateDomainAgentWithBody(ctx, uuid, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDomainAgentResponse(rsp)
}

func (c *ClientWithResponses) UpdateDomainAgentWithResponse(ctx context.Context, uuid DomainIdParam, params *UpdateDomainAgentParams, body UpdateDomainAgentJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDomainAgentOutput, error) {
	rsp, err := c.UpdateDomainAgent(ctx, uuid, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDomainAgentResponse(rsp)
}

// HostConfWithBodyWithResponse request with arbitrary body returning *HostConfResponse
func (c *ClientWithResponses) HostConfWithBodyWithResponse(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HostConfOutput, error) {
	rsp, err := c.HostConfWithBody(ctx, inventoryId, fqdn, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHostConfResponse(rsp)
}

func (c *ClientWithResponses) HostConfWithResponse(ctx context.Context, inventoryId HostId, fqdn Fqdn, params *HostConfParams, body HostConfJSONRequestBody, reqEditors ...RequestEditorFn) (*HostConfOutput, error) {
	rsp, err := c.HostConf(ctx, inventoryId, fqdn, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHostConfResponse(rsp)
}

// GetSigningKeysWithResponse request returning *GetSigningKeysResponse
func (c *ClientWithResponses) GetSigningKeysWithResponse(ctx context.Context, params *GetSigningKeysParams, reqEditors ...RequestEditorFn) (*GetSigningKeysResponse, error) {
	rsp, err := c.GetSigningKeys(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSigningKeysResponse(rsp)
}

// ParseListDomainsResponse parses an HTTP response from a ListDomainsWithResponse call
func ParseListDomainsResponse(rsp *http.Response) (*ListDomainsOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDomainsOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListDomainsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseRegisterDomainResponse parses an HTTP response from a RegisterDomainWithResponse call
func ParseRegisterDomainResponse(rsp *http.Response) (*RegisterDomainOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterDomainOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RegisterDomainResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateDomainTokenResponse parses an HTTP response from a CreateDomainTokenWithResponse call
func ParseCreateDomainTokenResponse(rsp *http.Response) (*CreateDomainTokenOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDomainTokenOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest DomainRegTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeleteDomainResponse parses an HTTP response from a DeleteDomainWithResponse call
func ParseDeleteDomainResponse(rsp *http.Response) (*DeleteDomainOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDomainOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseReadDomainResponse parses an HTTP response from a ReadDomainWithResponse call
func ParseReadDomainResponse(rsp *http.Response) (*ReadDomainOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReadDomainOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReadDomainResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateDomainUserResponse parses an HTTP response from a UpdateDomainUserWithResponse call
func ParseUpdateDomainUserResponse(rsp *http.Response) (*UpdateDomainUserOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDomainUserOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UpdateDomainUserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateDomainAgentResponse parses an HTTP response from a UpdateDomainAgentWithResponse call
func ParseUpdateDomainAgentResponse(rsp *http.Response) (*UpdateDomainAgentOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDomainAgentOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UpdateDomainAgentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseHostConfResponse parses an HTTP response from a HostConfWithResponse call
func ParseHostConfResponse(rsp *http.Response) (*HostConfOutput, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HostConfOutput{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HostConfResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetSigningKeysResponse parses an HTTP response from a GetSigningKeysWithResponse call
func ParseGetSigningKeysResponse(rsp *http.Response) (*GetSigningKeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSigningKeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReadKeysResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
